/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectogrupo67.Vistas;

import javax.swing.ImageIcon;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/VistasIcons/FondoG67.png"));
        Image image = icon.getImage();
        Desktop = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        }
        ;
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmFormularioAlumno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmFormularioMateria = new javax.swing.JMenuItem();
        jmAdminNotas = new javax.swing.JMenu();
        jmAdminInscripciones = new javax.swing.JMenuItem();
        jmCargaNotas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmListadoMaterias = new javax.swing.JMenuItem();
        MenuSALIR = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumno");

        jmFormularioAlumno.setText("Formulario de Alumno");
        jmFormularioAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormularioAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(jmFormularioAlumno);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materia");

        jmFormularioMateria.setText("Formulario de Materia");
        jmFormularioMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormularioMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(jmFormularioMateria);

        jMenuBar1.add(jMenu2);

        jmAdminNotas.setText("Administración");

        jmAdminInscripciones.setText("Manejo de inscipciones");
        jmAdminInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAdminInscripcionesActionPerformed(evt);
            }
        });
        jmAdminNotas.add(jmAdminInscripciones);

        jmCargaNotas.setText("Manipulacion de notas");
        jmCargaNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCargaNotasActionPerformed(evt);
            }
        });
        jmAdminNotas.add(jmCargaNotas);

        jMenuBar1.add(jmAdminNotas);

        jMenu6.setText("Consultas");

        jmListadoMaterias.setText("Alumnos por Materia");
        jmListadoMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListadoMateriasActionPerformed(evt);
            }
        });
        jMenu6.add(jmListadoMaterias);

        jMenuBar1.add(jMenu6);

        MenuSALIR.setText("Salir");
        MenuSALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSALIRMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuSALIR);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmFormularioAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormularioAlumnoActionPerformed
        
        Desktop.removeAll();
        Desktop.repaint();
        gestionAlumno venGestAlu = new gestionAlumno();
        venGestAlu.setVisible(true);
        Desktop.add(venGestAlu);
        Desktop.moveToFront(venGestAlu);
    }//GEN-LAST:event_jmFormularioAlumnoActionPerformed

    private void jmFormularioMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormularioMateriaActionPerformed
        Desktop.removeAll();
        Desktop.repaint();
        gestionMaterias venGestMat = new gestionMaterias();
        venGestMat.setVisible(true);
        Desktop.add(venGestMat);
        Desktop.moveToFront(venGestMat);
    }//GEN-LAST:event_jmFormularioMateriaActionPerformed

    private void jmAdminInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAdminInscripcionesActionPerformed
        Desktop.removeAll();
        Desktop.repaint();
        inscripciones venInsc = new inscripciones();
        venInsc.setVisible(true);
        Desktop.add(venInsc);
        Desktop.moveToFront(venInsc);
    }//GEN-LAST:event_jmAdminInscripcionesActionPerformed

    private void jmCargaNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCargaNotasActionPerformed
        Desktop.removeAll();
        Desktop.repaint();
        cargaNotas venCarNotas = new cargaNotas();
        venCarNotas.setVisible(true);
        Desktop.add(venCarNotas);
        Desktop.moveToFront(venCarNotas);
    }//GEN-LAST:event_jmCargaNotasActionPerformed

    private void jmListadoMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListadoMateriasActionPerformed
        Desktop.removeAll();
        Desktop.repaint();
        alumnosMaterias venListAlu = new alumnosMaterias();
        venListAlu.setVisible(true);
        Desktop.add(venListAlu);
        Desktop.moveToFront(venListAlu);
    }//GEN-LAST:event_jmListadoMateriasActionPerformed

    private void MenuSALIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSALIRMouseClicked
        ImageIcon icono = new ImageIcon("src/VistasIcons/salida32.png");
        int op = JOptionPane.showConfirmDialog(this, "Seguro desea salir",
                            "Salir", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, icono);
                    if (op == 0) {       
                        dispose();
                    }
    }//GEN-LAST:event_MenuSALIRMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu MenuSALIR;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmAdminInscripciones;
    private javax.swing.JMenu jmAdminNotas;
    private javax.swing.JMenuItem jmCargaNotas;
    private javax.swing.JMenuItem jmFormularioAlumno;
    private javax.swing.JMenuItem jmFormularioMateria;
    private javax.swing.JMenuItem jmListadoMaterias;
    // End of variables declaration//GEN-END:variables
}
